** 纯中文学习笔记
从子龙山人的21天教程开始学习。
* day 01
过一遍内置的教程，过一遍el in Y minutes 学习基本语法。 
学习几个基本设置。 安装几个主题。

=M-x linum-mode= 开启

- =C-x 3= 将当前窗口分到右边👉
- github 增加了token，又费劲增加了这个。否则无法push。😷
- 🤮hub网速真慢，教程上不去，准备换个网站了。或者自己搭建一个。




* day 02
实际上已经开始学习第二天的课程了，因为以前学过一次了，但是好多不用就忘记了。
- 中文字体不好看，不知道为什么？ 可以对比下wc code下的中文字体。
  
在 windows 环境下，emacs 的配置目录可以通过下面几种方式来设置：

If the environment variableHOME is set, use the directory it indicates.
If the registry entry HKCU\SOFTWARE\GNU\Emacs\HOME is set, use the directory it indicates.
If the registry entry HKLM\SOFTWARE\GNU\Emacs\HOME is set, use the directory it indicates. Not recommended, as it results in users sharing the same HOME directory.
If C:.emacs exists, then use C:/. This is for backward compatibility, as previous versions defaulted to C:/ if HOME was not set.
Use the user's AppData directory, usually a directory called Application Data under the user's profile directory, the location of which varies according to Windows version and whether the computer is part of a domain.

又找到了一个emacs配方：Centaur Emacs ：https://seagle0128.github.io/.emacs.d/ 
开始学习这个据说这个比较轻量级。是默认的快捷键。没有vim。 
从github是下载了很快，但是安装包就很慢。还在编译。有十分钟了吧。

* day 03

* day 06
** 一篇记笔记的博客文章
博文的原地址：https://dindi.garjola.net/zettelkustom.html
*** 题目：My zettelkustom (with Emacs, of course)
一下是原文的翻译，使用我自己的语言和理解。尽量不出现英文
**** 贼特是啥玩意？
好几年以前，我想要提高我的记笔记的能力，好做一点研究。我就发现了贼特卡斯滕方法，这个方法是一个德国的社会学家尼卡拉斯.路哈曼发明的，苏恩科.哈斯写的《怎样巧记笔记》这本书里有详细的介绍这个方法。
这个网站 https://zettelkasten.de/posts/overview/ 对此有简要的介绍。如果你对贼特卡斯滕方法感兴趣，在使用最后那个应用或者是Emacs之前，最好是先读一下阿斯的这本书。
总之，用几句话来概括贼特卡斯滕方法，就是您创建带有少量知识的笔记，这些知识是自给自足的。 这些笔记可能包含指向具有相关内容的其他笔记的链接。 这个想法是知识不是按层次结构组织的，而是在一个图表中，其中笔记指向其他笔记。
Zettelkasten方法让笔记是一个有生命的东西，定期添加笔记，最重要的是，通过重新组织内容、添加指向其他笔记的链接等，经常阅读和改进笔记。
贼特卡斯滕是你个人的，也只有你自己来编辑，她就像你的第二个大脑。
尼卡拉斯.路哈曼手写每个笔记，他个贼特笔记都是一个个的卡片。他还发明了独特的索引方法，使用特殊的结构来安排不同学科门类。这个网站https://niklas-luhmann-archiv.de/bestand/zettelkasten/suche有他的笔记样板。
为了实现数字化的贼特卡斯滕方法，一个能够在笔记之间创建链接的笔记应用程序。 一个不错的好处是为笔记添加标签以简化相关笔记集的搜索和生成。

专有软件市场上有许多支持 Zettelkasten 的创建和管理的应用程序。 也有免费软件同行。

Emacs 提供了几个包：
- Neuron Mode ， 使用马克党格式
- org-zettelkasten, 
- Zetteldeft, which use deft
- org-roam, based on org-mode and inspired by a commercial application.

可能还有其他我不知道的。 org-roam似乎是最受欢迎的一种。

在阅读了阿伦斯的书后，我决定尝试这种方法。 出于多种原因，我认为不想选择可用的 Emacs 软件包之一。 第一个是我不明白为什么除了普通的组织模式之外我还需要其他任何东西。 第二个是，在了解该方法如何以及是否对我有用之前，我不想承诺任何特定的实现。

**** 我是怎么做的


